#gamemode
PLAYER_FIRST = True
PVP_MODE = False

#constants
EMPTY  = 0
CIRCLE = 1
CROSS  = 2
SIZE   = 7
WIN    = 5
START_SIDE  = CROSS
DEPTH = 2
#ai variables
SCORE_LONGEST_MULTIPLIER = 10
SCORE_NEIGHBOUR_MULTIPLIER = 2
#neighbour
SCORE_NEIGHBOUR_ENEMY = 5
SCORE_NEIGHBOUR_FRIENDLY = 3
SCORE_NEIGHBOUR_EMPTY = 1
